quarkus:
  micrometer:
    export:
      prometheus:
        enabled: true
        path: /q/metrics
  rest-client:
    weather-openapi:
      url: https://api.openweathermap.org/data/2.5
      apikey: ${WEATHER_API_KEY}
      default-location: Ho Chi Minh City,vn

  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5435/postgres
    username: postgres
    password: postgres

  liquibase:
    schemas: public
    change-log: liquibase/changelog-master.xml
    change-log-scan: true
    migrate-at-start: true
    enabled: true

  scheduler:
    enabled: true

  http:
    port: 8080
