name: Gradle CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build process
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.4.2

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle (inject secret via ENV)
        env:
          QUARKUS_REST_CLIENT_WEATHER_OPENAPI_APIKEY: ${{ secrets.OPENWEATHER_API_KEY }}
        run: ./gradlew clean build --stacktrace

      - name: Run tests
        env:
          QUARKUS_REST_CLIENT_WEATHER_OPENAPI_APIKEY: ${{ secrets.OPENWEATHER_API_KEY }}
        run: ./gradlew test jacocoTestReport

      - name: Sonar (run on main)
        if: github.ref == 'refs/heads/main'
        run: |
          ./gradlew sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=alex-tran \
            -Dsonar.branch.name=main \
            -Dsonar.projectKey=alex-tran_weatherforecast \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.verbose=true